version: "3.6"

services:
  server:
    image: aeternity/governance-server
    restart: unless-stopped
    ports:
      - 3000:3000
    links:
      - redis
    environment:
      - CONTRACT_ADDRESS=ct_ouZib4wT9cNwgRA1pxgA63XEUd8eQRrG8PcePDEYogBc1VYTq
      - KEEP_HOT_INTERVAL=60000
      - MIDDLEWARE_URL=https://mainnet.aeternity.io/mdw
      - NODE_URL=https://mainnet.aeternity.io/
      - PORT=3000
      - REDIS_URL=redis://redis:6379
      - WEBSOCKET_URL=wss://mainnet.aeternity.io/mdw/websocket

  redis:
    image: redis
    restart: unless-stopped
    hostname: redis
