name: pull-request-cleanup

on:
  pull_request:
    branches: [ master ]
    types: [ closed ]

jobs:
  rollback-aepp:
    uses: aeternity/github-actions/.github/workflows/_rollback-gitops.yml@v2.3.1
    secrets: inherit
    with:
      DEPLOY_ENV: stg
      DEPLOY_APP: aepp-governance
      DEPLOY_VERSION: "pr-${{ github.event.number }}"
      DEPLOY_SUBDOMAIN: "pr-${{ github.event.number }}-governance"
  delete-tag-aepp:
    uses: aeternity/github-actions/.github/workflows/_delete-tag-ecr.yml@v2.3.1
    secrets: inherit
    with:
      REPOSITORY: "aepp-governance"
      TAG: "pr-${{ github.event.number }}"
  cleanup-aepp:
    uses: aeternity/github-actions/.github/workflows/_cleanup-ecr.yml@v2.3.1
    needs: [ delete-tag-aepp ]
    secrets: inherit
    with:
      REPOSITORY: aepp-governance
  rollback-server:
    uses: aeternity/github-actions/.github/workflows/_rollback-gitops.yml@v2.3.1
    needs: [ rollback-aepp ] # don't overlap GIT changes with the other rollback
    secrets: inherit
    with:
      DEPLOY_ENV: stg
      DEPLOY_APP: governance-server-testnet
      DEPLOY_VERSION: "pr-${{ github.event.number }}"
      DEPLOY_SUBDOMAIN: "pr-${{ github.event.number }}-governance-server-testnet"
  delete-tag-server:
    uses: aeternity/github-actions/.github/workflows/_delete-tag-ecr.yml@v2.3.1
    secrets: inherit
    with:
      REPOSITORY: "governance-server"
      TAG: "pr-${{ github.event.number }}"
  cleanup-server:
    uses: aeternity/github-actions/.github/workflows/_cleanup-ecr.yml@v2.3.1
    needs: [ delete-tag-server ]
    secrets: inherit
    with:
      REPOSITORY: governance-server
