name: release-server

on:
  push:
    tags: [ "governance-server-v*" ]

jobs:
  publish-server:
    uses: aeternity/github-actions/.github/workflows/_publish-ecr.yml@v2.3.1
    secrets: inherit
    with:
      FILE: ./governance-server/Dockerfile
      CONTEXT: .
      BUILD_ARGS: |
        GIT_REV=${{ github.ref_name }}
      REPOSITORY: "aeternity/governance-server"
  deploy-server-testnet:
    needs: [publish-server]
    uses: aeternity/github-actions/.github/workflows/_deploy-gitops.yml@v2.3.1
    secrets: inherit
    with:
      DEPLOY_ENV: prd
      DEPLOY_APP: governance-server-testnet
      DEPLOY_TAG: ${{ github.ref_name }}
  deploy-server-mainnet:
    needs: [publish-server, deploy-server-testnet]
    uses: aeternity/github-actions/.github/workflows/_deploy-gitops.yml@v2.3.1
    secrets: inherit
    with:
      DEPLOY_ENV: prd
      DEPLOY_APP: governance-server-mainnet
      DEPLOY_TAG: ${{ github.ref_name }}
