name: release-server

on:
  push:
    tags: [ "governance-server-v*" ]

concurrency: aepp-governance_production_environment

jobs:
  publish-server:
    uses: aeternity/github-actions/.github/workflows/_publish-ecr.yml@v2.4.0
    secrets: inherit
    with:
      FILE: ./governance-server/Dockerfile
      CONTEXT: .
      BUILD_ARGS: |
        GIT_REV=${{ github.ref_name }}
      REPOSITORY: "aeternity/governance-server"
  deploy-server-mainnet:
    needs: [publish-server]
    uses: aeternity/github-actions/.github/workflows/_deploy-gitops.yml@v2.4.0
    secrets: inherit
    with:
      DEPLOY_REPO: aeternity/gitops-apps-aelabs
      DEPLOY_ENV: prd
      DEPLOY_APP: governance-server-mainnet
      DEPLOY_TAG: ${{ github.ref_name }}
